### ISSUE TITLE
lp_algebraic_number_add has assertion failure when the inputs are actually dyadic rationals

### ISSUE THREAD

**Issue by dillonhuff** [SRI-CSL/libpoly#13]
When I try to construct algebraic numbers from dyadic rationals and then do arithmetic on them ```lp_algebraic_number_add``` crashes with an assertion failure.

For example, when I run  [this code](https://github.com/dillonhuff/algebraic_number_add_libpoly/blob/master/main.c) after compiling with "clang main.c -lpoly" I get the following:

```
Dyadic rationals
1
2
Algebraic numbers
1
2
Assertion failed: (a->f && b->f), function lp_algebraic_number_add, file /Users/dillon/CWorkspace/libpoly/src/number/algebraic_number.c, line 688.
Abort trap: 6
```

It looks like the algebraic number arithmetic functions like ``` lp_algebraic_number_add ``` don't handle the case where the algebraic number is actually just storing a rational number as a closed interval with ```f == 0```, even though functions like ``` lp_polynomial_roots_isolate ``` sometimes return algebraic numbers that are really rationals underneath the surface.

Before doing algebraic number arithmetic should we always check whether the numbers are actually just rationals and if so extract the rational values and do arithmetic on them?

**Comment by dddejan** [comment]
Thanks for reporting. I'll take a look and fix it, it's one of the cases that I never got to covering because they are not used as much. 

Since CAD is main main application, I normally use ``lp_value_t`` to abstract from the underlying representation (although there might also be hidden missing cases). In addition, in CAD construction arithmetic is not actually used so that part of the interface is not yet fully tested.
